#!/bin/sh

pushd ${OSRM_BUILD_DIR}
cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
      -DENABLE_MASON=${ENABLE_MASON:-OFF} \
      -DENABLE_NODE_BINDINGS=${ENABLE_NODE_BINDINGS:-OFF} \
      -DENABLE_CCACHE=ON \
      -DCMAKE_INSTALL_PREFIX=${OSRM_INSTALL_DIR} \
      -DENABLE_GLIBC_WORKAROUND=ON
make --jobs=${JOBS}
popd